<?php

namespace TeamSpeakLogs;

/**
 * Interface Report represents controller for generating views.
 * @package TeamSpeakLogs
 */
abstract class ReportController
{
    /**
     * Name of this report controller.
     *
     * @var string
     */
    private $name;

    /**
     * Slug of this report controller.
     *
     * @var string
     */
    private $slug;

    /**
     * Returns name of this report controller.
     *
     * @return string name of this report controller
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets the name of this report controller.
     *
     * @param string $name name of this report controller
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Returns this report controller's slug.
     *
     * @return string slug of this report controller
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Sets this report controller's slug.
     *
     * @param string $slug new slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * Processes one data.
     *
     * @param mixed $oneData one data to process
     * @return void
     */
    public abstract function process($oneData);

    /**
     * Returns view that is generated by this report controller.
     *
     * @return View resulting view
     */
    public abstract function generate();
}